version: '3.7' # Versión de docker-compose, depende de Docker
services:
  wp:
    image: wordpress
    ports:
      - 80:80
    volumes:
      - wp_data:/home/sinuhe/Curso23-24/ApWeb/WP/docker-compose-wp/volumes
    networks:
      - wp_net
    depends_on: # Ahora web depende de db
      - db
  db:
    image: mariadb
    volumes:
      - wpdb_data:/home/sinuhe/Curso23-24/ApWeb/WP/docker-compose-wp/volumes
    networks:
      - wp_net
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"
volumes:
    wp_data:
    wpdb_data:
networks:
    wp_net:
        driver: bridge